//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int studentID { get; set; }
        public string studentName { get; set; }
        public System.DateTime DOB { get; set; }
        public string StudentContact { get; set; }
        public string StudentRoll { get; set; }
        public string semester { get; set; }
        public string Subject { get; set; }
        public string status { get; set; }
    }
}
